name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4  # Update from v3 to v4
      
    - name: Set up Java
      uses: actions/setup-java@v4  # Update to latest version
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Create directories
      run: |
        mkdir -p $GITHUB_WORKSPACE/dependency-check/data
        mkdir -p $GITHUB_WORKSPACE/dependency-check/reports
        chmod -R 777 $GITHUB_WORKSPACE/dependency-check

    - name: Cache NVD Database
      uses: actions/cache@v4  # Update to v4
      with:
        path: $GITHUB_WORKSPACE/dependency-check/data
        key: nvd-${{ hashFiles('**/pom.xml') }}-${{ github.sha }}
        restore-keys: |
          nvd-${{ hashFiles('**/pom.xml') }}-
          nvd-

    - name: Download Dependency Check
      run: |
        wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.2/dependency-check-8.4.2-release.zip
        unzip dependency-check-8.4.2-release.zip
        chmod +x dependency-check/bin/dependency-check.sh

    - name: Run Dependency Check
      run: |
        ./dependency-check/bin/dependency-check.sh \
          --scan $GITHUB_WORKSPACE \
          --format "HTML" "JSON" \
          --out $GITHUB_WORKSPACE/dependency-check/reports \
          --data $GITHUB_WORKSPACE/dependency-check/data \
          --enableExperimental \
          --suppression $GITHUB_WORKSPACE/suppress.xml

    - name: Upload Scan Results
      uses: actions/upload-artifact@v4  # Update to v4
      if: always()
      with:
        name: dependency-check-report
        path: ${{ github.workspace }}/dependency-check/reports/
        retention-days: 5
